# Generated by Django 3.1.5 on 2021-03-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210319_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_categ_id',
            field=models.ForeignKey(blank=True, default='Category', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.category'),
        ),
    ]
