# Generated by Django 3.1.7 on 2021-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210403_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
