# Generated by Django 3.1.7 on 2021-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_searchimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchimage',
            name='search_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
