# Generated by Django 3.1.7 on 2021-04-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_offer_offer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='offers'),
        ),
    ]
