# Generated by Django 3.1.7 on 2021-05-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_product_is_offer'),
        ('listings', '0011_auto_20210419_1705'),
    ]

    operations = [
    ]
