# Generated by Django 3.1.7 on 2021-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_orderoffer'),
        ('listings', '0016_merge_20210504_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_product',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer_product',
            name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchimage',
            name='search_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Offer_Product',
        ),
    ]
