# Generated by Django 3.1.7 on 2021-05-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_offer_brands'),
        ('listings', '0017_auto_20210507_2204'),
    ]

    operations = [
    ]
