# Generated by Django 3.1.7 on 2021-05-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_merge_20210508_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
