# Generated by Django 3.1.7 on 2021-05-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20210514_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
