# Generated by Django 3.1.7 on 2021-05-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.product'),
        ),
    ]
