# Generated by Django 3.1.7 on 2021-05-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210419_1431'),
        ('orders', '0003_orderoffer'),
    ]

    operations = [
    ]
