# Generated by Django 3.1.7 on 2021-04-01 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0006_auto_20210402_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('lbp', 'LBP')], default='lbp', max_length=10)),
                ('from_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('to_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offer.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.product')),
            ],
        ),
    ]
