# Generated by Django 3.1.5 on 2021-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.TextField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('cashier', 'Cashier')]),
        ),
    ]
